# Generated by Django 4.0.4 on 2022-06-02 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_corousal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='corousal',
        ),
    ]
