# Generated by Django 4.0.4 on 2022-06-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_corousal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CROUSAL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=50)),
                ('imagetext', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('image', models.ImageField(default='', upload_to='base/images')),
            ],
        ),
    ]
