# Generated by Django 4.0.4 on 2022-06-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_crousal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_image', models.ImageField(default='', upload_to='base/images')),
                ('ac_title', models.CharField(max_length=50)),
                ('ac_subtitle', models.CharField(max_length=50)),
                ('ac_desc_p1', models.CharField(max_length=300)),
                ('ac_desc_p2', models.CharField(max_length=300)),
                ('ac_link', models.CharField(max_length=300)),
            ],
        ),
    ]
