# Generated by Django 4.0.4 on 2022-06-03 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_speciality_alter_ac_ac_desc_p1_alter_ac_ac_desc_p2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speciality',
            name='link_color',
            field=models.CharField(default='', max_length=30),
        ),
    ]
