# Generated by Django 4.0.4 on 2022-06-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_logo', models.ImageField(default='', upload_to='base/images')),
                ('sp_logoname', models.CharField(max_length=50)),
            ],
        ),
    ]
